export interface Sponsor {
  name: string;
  image: string;
  description: string;
  github?: string;
  linkedin?: string;
  twitter?: string;
  instagram?: string;
  isPastSponsor?: boolean;
  isWeSponsor?: boolean;
}

const sponsors: Sponsor[] = [
  {
    name: "Hideo",
    image: "https://avatars.githubusercontent.com/u/27260158?v=4",
    description: "Fullstack developer",
    github: "https://github.com/hideo0106",
  },
  {
    name: "Tyros625",
    image: "https://avatars.githubusercontent.com/u/208297512?v=4",
    description: "Opensource developer",
    github: "https://github.com/Tyros625",
  },
  {
    name: "Rat spott",
    image: "https://avatars.githubusercontent.com/u/4381687?v=4",
    description: "Opensource developer",
    github: "https://github.com/ratspott",
    twitter: "https://x.com/tomas.photo",
  },
  {
    name: "Tupui",
    image: "https://avatars.githubusercontent.com/u/2808342?v=4",
    description: "Senior full stack",
    github: "https://github.com/creative-tupui",
  },
  {
    name: "Aqua Commander",
    image: "https://avatars.githubusercontent.com/u/7747717?v=4",
    description: "Blockchain Engineer",
    github: "https://github.com/aquacommander",
  },
  {
    name: "Bluesora dev ",
    image: "https://avatars.githubusercontent.com/u/8726178?v=4",
    description: "Opensource developer",
    github: "https://github.com/bluesoradev",
  },
  {
    name: "Toptal dev",
    image: "https://avatars.githubusercontent.com/u/19962154?v=4",
    description: "Opensource developer",
    github: "https://github.com/toptaldev5",
  },
  {
    name: "Alpha",
    image: "https://avatars.githubusercontent.com/u/41268896?v=4",
    description: "Opensource developer",
    github: "https://github.com/FIFA0313",
  },
  {
    name: "Tenosia",
    image: "https://avatars.githubusercontent.com/u/45573545?v=4",
    description: "Opensource developer",
    github: "https://github.com/Tenosia",
  },
  {
    name: " Timothy Strebing",
    image: "https://avatars.githubusercontent.com/u/45822735?v=4",
    description: "Opensource developer",
    github: "https://github.com/tstrebing",
  },
  {
    name: " Pragmaj Upit",
    image: "https://avatars.githubusercontent.com/u/46350287?v=4",
    description: "Fullstack developer",
    github: "https://github.com/pragmajupit",
  },
  {
    name: " Blockchain Developer",
    image: "https://avatars.githubusercontent.com/u/50129289?v=4",
    description: "Opensource developer",
    github: "https://github.com/FIFA0313",
  },

  {
    name: "Zephyr",
    image: "https://avatars.githubusercontent.com/u/55862076?v=4",
    description: "Fullstack developer",
    github: "https://github.com/Zephyr3311",
  },

  {
    name: "Nsracer",
    image: "https://avatars.githubusercontent.com/u/59646019?v=4",
    description: "Fullstack developer",
    github: "https://github.com/Nsracer",
  },

  {
    name: "phil1 px",
    image: "https://avatars.githubusercontent.com/u/12487735?v=4",
    description: "Fullstack developer",
    github: "https://github.com/phil1px",
  },

  {
    name: "Yupsecous",
    image: "https://avatars.githubusercontent.com/u/13575761?v=4",
    description: "Software Engineer",
    github: "https://github.com/Yupsecous",
  },

  {
    name: "Logic Mason",
    image: "https://avatars.githubusercontent.com/u/33540416?v=4",
    description: "Fullstack developer",
    github: "https://github.com/LogicMason5",
  },

  {
    name: "Meta core",
    image: "https://avatars.githubusercontent.com/u/34447785?v=4",
    description: "Fullstack developer",
    github: "https://github.com/metacore-stack",
  },

  {
    name: "UC-techie",
    image: "https://avatars.githubusercontent.com/u/46532433?v=4",
    description: "Python Developer",
    github: "https://github.com/UC-techie",
  },

  {
    name: "Helious Matt",
    image: "https://avatars.githubusercontent.com/u/47945257?v=4",
    description: "Blockchain developer",
    github: "https://github.com/helious225",
  },
  
  {
    name: "CodyOnGit",
    image: "https://avatars.githubusercontent.com/u/56834721?v=4",
    description: "Fullstack developer",
    github: "https://github.com/CodyOnGit",
  },
  
  {
    name: "DevXavier",
    image: "https://avatars.githubusercontent.com/u/192259212?v=4",
    description: "Student ",
    github: "https://github.com/DevXavierNieto",
  },

  {
    name: "Kriti Raj",
    image: "https://avatars.githubusercontent.com/u/62815511?v=4",
    description: "Full Stack Developer",
    github: "https://github.com/kriti-raj",
    isPastSponsor: true,
  },
  {
    name: "Judar",
    image: "https://avatars.githubusercontent.com/u/75671199?v=4",
    description: "Student ",
    github: "https://github.com/trongphuhappy",
    twitter: "https://x.com/Judar_Clitus",
    isPastSponsor: true,
  },
  {
    name: "Jisha TR",
    image: "https://avatars.githubusercontent.com/u/82383735?v=4",
    description: "Student ",
    github: "https://github.com/Jisha-tr",
    isPastSponsor: true,
  },
  {
    name: "Aryan Jaiswal",
    image: "https://avatars.githubusercontent.com/u/72207299?v=4",
    description: "Student ",
    github: "hhttps://github.com/Aryanjstar",
    isPastSponsor: true,
  },
  {
    name: "The Sting",
    image: "https://avatars.githubusercontent.com/u/163915232?v=4",
    description: "Cybersecurity",
    github: "https://github.com/TheStingR",
    isPastSponsor: true,
  },
  {
    name: "Kmanci",
    image: "https://avatars.githubusercontent.com/u/40892999?v=4",
    description: "Kazım",
    github: "https://github.com/jhealerbb",
    isPastSponsor: true,
  },
  {
    name: "Happy mdev",
    image: "https://avatars.githubusercontent.com/u/68038057?v=4",
    description: "Software Engineer",
    github: "https://github.com/0xhappydev",
    isPastSponsor: true,
  },
  {
    name: "Ateeq ur Rehman",
    image: "https://avatars.githubusercontent.com/u/76849373?v=4",
    description: "AI Engineer",
    github: "https://github.com/ateeq-mughal",
    isPastSponsor: true,
  },

  {
    name: "Austin Jian",
    image: "https://avatars.githubusercontent.com/u/135089334?v=4",
    description: "Student ",
    github: "https://github.com/austinjiann",
    isPastSponsor: true,
  },

  {
    name: "Ayokanmi Adejola",
    image: "https://avatars.githubusercontent.com/u/191106326?v=4",
    description: "Developer at Softlyft",
    github: "https://github.com/Ayokanmi-Adejola",
    linkedin: "https://www.linkedin.com/in/ayokanmiadejola/",
    twitter: "https://x.com/AyoAdejola100",
    isPastSponsor: true,
  },

  {
    name: "Matheus Farias",
    image: "http://avatars.githubusercontent.com/u/22086460?v=4",
    description: "Student",
    github: "https://github.com/MatheusFarias8",
    isPastSponsor: true,
  },
  {
    name: "superdevp",
    image: "https://avatars.githubusercontent.com/u/202645405?v=4",
    description: "Web Developer",
    github: "https://github.com/superdevp",
    isPastSponsor: true,
  },
  {
    name: "MeeTy HA",
    image: "https://avatars.githubusercontent.com/u/196355500?v=4",
    description: "Student ",
    github: "https://github.com/MeeTyHA",
    isPastSponsor: true,
  },
  {
    name: "milos matovicup",
    image: "https://avatars.githubusercontent.com/u/184030535?v=4",
    description: "Student",
    github: "https://github.com/milosmatovicup",
    isPastSponsor: true,
  },
  {
    name: "Tirth Patel",
    image: "https://avatars.githubusercontent.com/u/111308497?v=4",
    description: "Student",
    github: "https://github.com/TirthWillLearn",
    linkedin: "https://www.linkedin.com/in/tirth-k-patel/",
    twitter: "https://x.com/codewithtirth",
    isPastSponsor: true,
  },

  {
    name: "Takashi Arai",
    image: "https://avatars.githubusercontent.com/u/42265874?v=4",
    description: "Student Ryukyu Uni, Japan",
    github: "https://github.com/arataka1313",
    linkedin: "https://www.linkedin.com/in/takashi-arai-2b697b360/",
    twitter: "https://x.com/jjackofall",
    isPastSponsor: true,
  },
  {
    name: "Sumit Khanna",
    image: "https://avatars.githubusercontent.com/u/29749122?v=4",
    description: "Developer at slickspender",
    github: "https://github.com/jjackofall",
    twitter: "https://x.com/jjackofall",
    isPastSponsor: true,
  },
  {
    name: "Prakhar Saxena",
    image: "https://avatars.githubusercontent.com/u/111764688?v=4",
    description: "Studying @McMaster University",
    github: "https://www.linkedin.com/in/prakharsaxena5/",
    linkedin: "https://www.linkedin.com/in/prakharsaxena5/",
    isPastSponsor: true,
  },

  {
    name: "Varghese Baby",
    image: "https://avatars.githubusercontent.com/u/68038057?v=4",
    description: "Software Developer",
    github: "https://github.com/varghese25",
    linkedin: "https://www.linkedin.com/in/varghese-baby-138429175/",
    isPastSponsor: true,
  },

  {
    name: "Carlos Romero",
    image: "https://avatars.githubusercontent.com/u/119690391?v=4",
    description: "CS Student of La Salle",
    github: "https://github.com/carlosromerorodriguez",
    linkedin: "https://www.linkedin.com/in/carlos-romero-rdgz/",
    isPastSponsor: true,
  },
  {
    name: "Yahya Banouk",
    image: "https://avatars.githubusercontent.com/u/83559441?v=4",
    description: "Full-Stack Engineer at Expersi",
    github: "https://github.com/yahya-banouk",
    linkedin: "https://x.com/Yahya_Banouk",
    twitter: "https://x.com/Yahya_Banouk",
    isPastSponsor: true,
  },
  {
    name: "Mike ",
    image: "https://avatars.githubusercontent.com/u/79911993?v=4",
    description: "AI Consultant",
    github: "#",
    linkedin: "#",
    isPastSponsor: true,
  },
  {
    name: "Alex Choi",
    image: "https://avatars.githubusercontent.com/u/64334999?v=4",
    description: "Legacy sponsor",
    github: "https://github.com/alexechoi",
    linkedin: "https://www.linkedin.com/in/alexchoi1/",
    twitter: "https://x.com/alexchhk",
    isPastSponsor: true,
  },
  {
    name: "Renato Maynard",
    image: "https://avatars.githubusercontent.com/u/79546214?v=4",
    description: "M.Sc. in Operations Research",
    github: "https://www.linkedin.com/in/renatomaynardetche/",
    linkedin: "#",
    twitter: "#",
    isPastSponsor: true,
  },
  {
    name: "Tram Khoi Nguyen",
    image: "https://avatars.githubusercontent.com/u/112838098?v=4",
    description: "Student at Tra Vinh, Vietnam",
    github: "https://github.com/khoinguyennni",
    linkedin: "#",
    twitter: "#",
    isPastSponsor: true,
  },
  {
    name: "Bobby Azad",
    image: "https://avatars.githubusercontent.com/u/48394338?v=4",
    description: "BI Developer at Agtegra",
    github: "https://github.com/gbazad93",
    linkedin: "https://www.linkedin.com/in/bobby-azad-b2035b65/",
    twitter: "#",
    isPastSponsor: true,
  },
  {
    name: "Sudarshan Giri",
    image: "https://avatars.githubusercontent.com/u/41857483?v=4",
    description: "Drupal Developer at Webfirst",
    github: "hhttps://github.com/SudarshanGiri",
    linkedin: "https://www.linkedin.com/in/sudarshangiri/",
    twitter: "https://x.com/sudarshanhang",
    isPastSponsor: true,
  },
  {
    name: "Aryan Jaiswal",
    image:
      "https://pbs.twimg.com/profile_images/1921606118683426816/M1mU3vm8_400x400.jpg",
    description: "Founder @MLSA",
    github: "https://github.com/Aryanjstar",
    linkedin: "https://www.linkedin.com/in/aryanjstar/",
    twitter: "https://x.com/Aryanjstar",
    isPastSponsor: true,
  },
  {
    name: "Kashif Khan",
    image: "https://avatars.githubusercontent.com/u/88695658?v=4",
    description: "Quality Assurance Engineer",
    github: "https://github.com/KashifKhaan",
    linkedin: "https://www.linkedin.com/in/mr-kashif-442146214/",
    twitter: "https://x.com/KaxhifKhan",
    isPastSponsor: true,
  },
  {
    name: "Judar",
    image:
      "https://pbs.twimg.com/profile_images/1625875289795604480/Vghp-Ym6_400x400.jpg",
    description: "Founder @MLSA",
    github: "https://github.com/trongphuhappy",
    linkedin: "#",
    twitter: "https://x.com/Judar_Clitus",
    isPastSponsor: true,
  },
  {
    name: "Kriti Raj",
    image: "https://avatars.githubusercontent.com/u/62815511?v=4",
    description: "Student at IIIT , India",
    github: "https://github.com/kriti-raj",
    linkedin: "https://www.linkedin.com/in/kritirajtech/",
    twitter: "https://x.com/kriti___raj",
    isPastSponsor: true,
  },
  {
    name: "Alex Cerezo",
    image: "https://avatars.githubusercontent.com/u/92682715?v=4",
    description: "Software Engineer at Outlier",
    github: "https://github.com/alexcerezo",
    linkedin: "https://www.linkedin.com/in/alexcerezocontreras/",
    twitter: "https://x.com/alexcerezx",
    isPastSponsor: true,
  },
  {
    name: "Monojit Pal",
    image: "https://avatars.githubusercontent.com/u/144504389?v=4",
    description: "Student at St. Thomas' College",
    github: "https://github.com/Monojit-Pal",
    linkedin: "https://www.linkedin.com/in/pal-monojit/",
    twitter: "https://x.com/Monojit__18",
    isPastSponsor: true,
  },
  {
    name: "Chiluka Akshitha",
    image: "https://avatars.githubusercontent.com/u/120377576?v=4",
    description: "Student at IIT Madras",
    github: "https://github.com/AKSHITHA-CHILUKA",
    linkedin: "https://www.linkedin.com/in/akshitha-chiluka-b19245259",
    twitter: "https://x.com/AkshithaChiluka?t=5ztRGbV2DDB6Wf5tlCyHrw&s=09",
    isPastSponsor: true,
  },

  {
    name: "Medha",
    image: "https://avatars.githubusercontent.com/u/90996890?v=4",
    description: "Student: NextJs Developer",
    github: "https://github.com/medss19",
    linkedin: "https://www.linkedin.com/in/medha-agarwal-01b33725a/",
    isWeSponsor: true,
  },
  {
    name: "Aadil Latif",
    image: "https://avatars.githubusercontent.com/u/145087959?v=4",
    description: "Founder TechXNinjas",
    github: "https://github.com/iaadillatif",
    linkedin: "https://www.linkedin.com/in/iaadillatif/",
    isWeSponsor: true,
  },

  {
    name: "Richa jaishwal",
    image: "https://avatars.githubusercontent.com/u/156594333?v=4",
    description: "MERN Developer",
    github: "https://github.com/Richajaishwal0",
    linkedin: "https://www.linkedin.com/in/richa-jaishwal/",
    isWeSponsor: true,
  },

  {
    name: "Aditya Singh",
    image: "https://avatars.githubusercontent.com/u/148507838?v=4",
    description: "Software Developer",
    github: "https://github.com/singh-odyssey",
    linkedin: "linkedin.com/m/in/aditya-singh-6297242a5",
    isWeSponsor: true,
  },
  {
    name: "GSSoC24",
    image: "https://avatars.githubusercontent.com/u/166525102?s=200&v=4",
    description: "Open Source Community",
    github: "https://github.com/GSSoC24",
    isWeSponsor: true,
  },
  {
    name: "Kanishka Panwar",
    image: "https://avatars.githubusercontent.com/u/172115852?v=4",
    description: "MERN Developer",
    github: "https://github.com/kanishka-commits",
    linkedin: "https://www.linkedin.com/in/kanishka03p/",
    twitter: "https://x.com/kanishka03p",
    isWeSponsor: true,
  },
  {
    name: "Suryansh Mishra",
    image: "https://avatars.githubusercontent.com/u/180032733?v=4",
    description: "MERN Developer",
    github: "https://github.com/smirk-dev",
    linkedin: "https://www.linkedin.com/in/connectwithsuryanshmishra/",
    isWeSponsor: true,
  },
  {
    name: "Anuj Kulkarni",
    image: "https://avatars.githubusercontent.com/u/192874339?v=4",
    description: "MERN Developer",
    github: "https://github.com/steam-bell-92",
    linkedin: "https://www.linkedin.com/in/anuj-chandrakant-kulkarni/",
    twitter: "https://x.com/AnujKulkarni040",
    isWeSponsor: true,
  },

  {
    name: "Sonal Yadav",
    image: "https://avatars.githubusercontent.com/u/169170929?v=4",
    description: "Web & App Developer",
    github: "https://github.com/sonalyadav1",
    linkedin: "https://www.linkedin.com/in/sonal-yadav-193471238/",
    twitter: "https://x.com/SonalYa944317",
    isWeSponsor: true,
  },
  {
    name: "Ayokanmi Adejola",
    image: "https://avatars.githubusercontent.com/u/191106326?v=4",
    description: "Final Year Student",
    github: "https://github.com/Ayokanmi-Adejola",
    linkedin: "hhttps://www.linkedin.com/in/ayokanmiadejola/",
    twitter: "https://x.com/AyoAdejola100",
    isWeSponsor: true,
  },

  {
    name: "Nishant Rana",
    image: "https://avatars.githubusercontent.com/u/126577697?v=4",
    description: "Final Year Student",
    github: "https://github.com/NishantRana07",
    linkedin: "https://www.linkedin.com/in/nishantrana07/",
    twitter: "https://x.com/TechwNishant",
    isWeSponsor: true,
  },

  {
    name: "Ankit Modanwal",
    image: "https://avatars.githubusercontent.com/u/166202965?v=4",
    description: "Next.js & ML Developer ",
    github: "https://github.com/ankitmodanwall",
    linkedin: "https://www.linkedin.com/in/ankit-modanwal/",
    twitter: "https://x.com/ankitt_ml",
    isWeSponsor: true,
  },

  {
    name: "Irfan",
    image: "https://avatars.githubusercontent.com/u/138690953?v=4",
    description: "Final Year Student",
    github: "https://github.com/iitzIrFan",
    linkedin: "https://www.linkedin.com/in/irfan-shaikh-8b5b94259/",
    twitter: "https://x.com/iitzIrfan",
    isWeSponsor: true,
  },
  {
    name: "Renato Maynard",
    image: "https://avatars.githubusercontent.com/u/79546214?v=4",
    description: "M.Sc. in Operations Research",
    github: "https://www.linkedin.com/in/renatomaynardetche/",
    twitter: "https://x.com/codewithdhruba",
    isWeSponsor: true,
  },

  {
    name: "Dhrubaraj Pati",
    image: "https://avatars.githubusercontent.com/u/146111647?v=4",
    description: "Student at SVU",
    github: "https://github.com/codewithdhruba01",
    linkedin: "#",
    twitter: "#",
    isWeSponsor: true,
  },
  {
    name: "Carlos Romero",
    image: "https://avatars.githubusercontent.com/u/119690391?v=4",
    description: "CS Student of La Salle",
    github: "https://github.com/carlosromerorodriguez",
    linkedin: "https://www.linkedin.com/in/carlos-romero-rdgz/",
    isWeSponsor: true,
  },
  {
    name: "Shivansh Saxena",
    image: "https://avatars.githubusercontent.com/u/112249407?v=4",
    description: "Intern at Geo Softech",
    github: "https://github.com/ShivanshPlays",
    linkedin: "https://www.linkedin.com/in/shivansh-saxena-288785168/",
    isWeSponsor: true,
  },
  {
    name: "Mastan Sayyad",
    image: "https://avatars.githubusercontent.com/u/101971980?v=4",
    description: "Web Deveoper at SWOC",
    github: "https://github.com/MastanSayyad",
    linkedin: "https://www.linkedin.com/in/mastan-sayyad/",
    twitter: "https://x.com/mastansayyad02",
    isWeSponsor: true,
  },
  {
    name: "recode hive",
    image: "/img/logo.svg",
    description: "Open Source Community",
    github: "https://github.com/recodehive",
    linkedin: "https://www.linkedin.com/company/recode-hive/",
    twitter: "https://x.com/recodehive",
    isWeSponsor: true,
  },
  {
    name: "Anshika Tiwari",
    image: "https://avatars.githubusercontent.com/u/143124119?v=4",
    description: "Student, ",
    github: "https://github.com/anshikatiwari20",
    linkedin: "https://www.linkedin.com/in/anshika-tiwari-/",
    twitter: "https://x.com/anshikat_20",
    isWeSponsor: true,
  },
  {
    name: "Meet Jain",
    image: "https://avatars.githubusercontent.com/u/133582566?v=4",
    description: "Student @ IIIT Jabalpur",
    github: "https://github.com/Meetjain1",
    linkedin: "https://www.linkedin.com/in/meet-jain-413015265/",
    twitter: "https://x.com/Meetjain_100",
    isWeSponsor: true,
  },
  {
    name: "Hemant Lohar",
    image: "https://avatars.githubusercontent.com/u/131635107?v=4",
    description: "Student, India",
    github: "https://github.com/Hemantlohar",
    linkedin: "#",
    isWeSponsor: true,
  },
  {
    name: "Chiluka Akshitha",
    image: "https://avatars.githubusercontent.com/u/120377576?v=4",
    description: "Student at IIT Madras",
    github: "https://github.com/AKSHITHA-CHILUKA",
    linkedin: "https://www.linkedin.com/in/akshitha-chiluka-b19245259",
    twitter: "https://x.com/AkshithaChiluka?t=5ztRGbV2DDB6Wf5tlCyHrw&s=09",
    isWeSponsor: true,
  },
  {
    name: "Himangshu Sharma",
    image: "https://avatars.githubusercontent.com/u/120270398?v=4",
    description: "Opensource developer",
    github: "https://github.com/HimangshuSharma01",
    linkedin: "https://www.linkedin.com/in/himangshusharma01",
    isWeSponsor: true,
  },
  {
    name: "Siddheya Kulkarni",
    image: "https://avatars.githubusercontent.com/u/115717746?v=4",
    description: "Student, Opensource developer",
    github: "https://github.com/Asymtode712",
    linkedin: "https://www.linkedin.com/in/siddheya-kulkarni/",
    twitter: "https://x.com/SidKulkarni712",
    isWeSponsor: true,
  },
  {
    name: "Prithwi Hegde",
    image: "https://avatars.githubusercontent.com/u/115262737?v=4",
    description: "Student at JSSSSU",
    github: "https://github.com/Prithwi32",
    linkedin: "https://www.linkedin.com/in/prithwi-hegde/",
    isWeSponsor: true,
  },
  {
    name: "Vansh Chaurasiya",
    image: "https://avatars.githubusercontent.com/u/114163734?v=4",
    description: "Intern at GoComet",
    github: "https://github.com/vansh-codes",
    linkedin: "https://www.linkedin.com/in/vanshchaurasiya24/",
    twitter: "https://x.com/VanshChaurasiy4",
    isWeSponsor: true,
  },
  {
    name: "Hemanth kumar",
    image: "https://avatars.githubusercontent.com/u/106808387?v=4",
    description: "Community Leader at recode hive",
    github: "https://github.com/Hemu21",
    linkedin: "https://www.linkedin.com/in/hemu21/",
    twitter: "https://x.com/Hemu21_",
    isWeSponsor: true,
  },
  {
    name: "Eduardo San Martin",
    image: "https://avatars.githubusercontent.com/u/664177?v=4",
    description: "Member of the @vuejs",
    github: "https://github.com/posva",
    twitter: "https://x.com/posva",
    isWeSponsor: true,
  },
  {
    name: "Md Azfar Alam",
    image: "https://avatars.githubusercontent.com/u/100375390?v=4",
    description: "Devops Engineer",
    github: "https://github.com/mdazfar2",
    linkedin: "https://www.linkedin.com/in/md-azfar-alam/",
    twitter: "https://x.com/azfarxx_",
    isWeSponsor: true,
  },
  {
    name: "Ajay Dhangar",
    image: "https://avatars.githubusercontent.com/u/99037494?v=4",
    description: "Founder at CodeHarborHub",
    github: "https://github.com/ajay-dhangar",
    linkedin: "https://www.linkedin.com/in/ajay-dhangar/",
    twitter: "https://x.com/CodesWithAjay",
    isWeSponsor: true,
  },
  {
    name: "Sneha kumari",
    image: "https://avatars.githubusercontent.com/u/95492939?v=4",
    description: "Developer at GHCL",
    github: "https://github.com/Snehsk",
    linkedin: "https://www.linkedin.com/in/sneha-kumari1/",
    isWeSponsor: true,
  },
  {
    name: "Swarnendu Bhandari",
    image:
      "https://avatars.githubusercontent.com/u/56834721?v=4",
    description: "Student at IIT Kharagpur",
    github: "https://github.com/swrno",
    twitter: "https://x.com/Swarnendu___",
    linkedin: "https://www.linkedin.com/in/swarnendu-bhandari/",
    isWeSponsor: true,
  },
  {
    name: "Alex Cerezo",
    image: "https://avatars.githubusercontent.com/u/92682715?v=4",
    description: "Developer at Outlier",
    github: "https://github.com/alexcerezo",
    linkedin: "https://www.linkedin.com/in/alexcerezocontreras",
    twitter: "https://x.com/alexcerezx",
    isWeSponsor: true,
  },
  {
    name: "Aditya Bhaumik",
    image: "https://avatars.githubusercontent.com/u/92214013?v=4",
    description: "Student at VIT",
    github: "https://github.com/aditya-bhaumik",
    linkedin: "https://www.linkedin.com/in/aditya-bhaumik-62b6b2220/",
    isWeSponsor: true,
  },
  {
    name: "Vivek Vardhan",
    image: "https://avatars.githubusercontent.com/u/91594529?v=4",
    description: "Student at VIT",
    github: "https://github.com/vivekvardhan2810",
    linkedin: "https://www.linkedin.com/in/vivek-vardhan-23682521b/",
    isWeSponsor: true,
  },
  {
    name: "Dinesh Talwadker",
    image:
      "https://avatars.githubusercontent.com/u/12487735?v=4",
    description: "Co-Founder at Sanity Esports",
    github: "https://github.com/dinxsh",
    linkedin: "https://www.linkedin.com/in/dineshtalwadker/",
    twitter: "https://x.com/dineshcodes",
    isWeSponsor: true,
  },
  {
    name: "Sanya Dureja",
    image: "https://avatars.githubusercontent.com/u/84080312?v=4",
    description: "SDE at Paypal",
    github: "https://github.com/sanyadureja",
    linkedin: "https://www.linkedin.com/in/sanya-dureja-13960122a/",
    isWeSponsor: true,
  },
  {
    name: "Razvan Stoenescu",
    image: "https://avatars.githubusercontent.com/u/4665641?v=4",
    description: "Team lead of Quasar Framework",
    github: "https://github.com/rstoenescu",
    isWeSponsor: true,
  },
  {
    name: "Sarah Drasner",
    image: "https://avatars.githubusercontent.com/u/2281088?v=4",
    description: "Director at Google",
    github: "https://github.com/sdras",
    twitter: "https://x.com/sarah_edo",
    isWeSponsor: true,
  },
  {
    name: "Homebrew",
    image: "https://avatars.githubusercontent.com/u/1503512?s=200&v=4",
    description: "package manager for macOS",
    github: "https://github.com/Homebrew",
    isWeSponsor: true,
  },
  {
    name: "Aditya Singh Rathore",
    image: "https://avatars.githubusercontent.com/u/142787780?v=4",
    description: "Data Engineer",
    github: "https://github.com/Adez017",
    linkedin: "https://www.linkedin.com/in/aditya-singh-rathore0017/",
    twitter: "https://x.com/Adez017",
    isWeSponsor: true,
  },
  {
    name: "Mehfooj A",
    image: "https://avatars.githubusercontent.com/u/162735469?v=4",
    description: "Opensouce Contributor",
    github: "https://github.com/tsvlgd",
    linkedin: "https://www.linkedin.com/in/mehfooj-a-b6aa0b243/",
    isWeSponsor: true,
  },
  {
    name: "Abhash Chakraborty",
    image: "https://avatars.githubusercontent.com/u/80592559?v=4",
    description: "Opensouce Contributor",
    github: "https://github.com/Abhash-Chakraborty",
    linkedin: "https://www.linkedin.com/in/abhash-chakraborty-b78862247/",
    isWeSponsor: true,
  },
  
];

export default sponsors;
